version: '3'


services:
  minio:
    image: bitnami/minio
    container_name: minio
    hostname: minio
    restart: always
    volumes:
      - './minio/data:/bitnami/minio/data'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=$MINIO_PASSWORD
      - MINIO_DEFAULT_BUCKETS=$DEFAULT_BUCKET_NAME
      - MINIO_HTTP_TRACE=/dev/stdout
      
  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    hostname: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "$HTTP_PORT:80"
      - "$HTTPS_PORT:443"

