apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-cert
  namespace: minio
spec:
  secretName: minio-tls
  commonName: "dev.file.hosting.jumpai.tech"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-stage
  dnsNames:
  - "dev.file.hosting.jumpai.tech"
  - "dev.file-console.hosting.jumpai.tech"
